Repository buildo/metarpheus-io-ts, pull requests merged in 2018-07, with the labels that each got.

#46 Polishing
  package.json
  src/domain.ts
  src/index.ts
  tslint.json
  typings-checker/index.ts
  typings-checker/tsconfig.json
Labels: waiting for merge

#45 Use Reader from fp-ts for injecting dependencies
  package.json
  src/domain.ts
  src/index.ts
  test/expected-model1.txt
  test/expected-model4.txt
  tslint.json
  typings-checker/index.ts
  typings-checker/tsconfig.json
Labels: WIP

#47 More polishing
  src/index.ts
  test/expected-model1.txt
  test/expected-model4.txt
Labels: waiting for merge

#44 Add support for generics
  README.md
  output/index.ts
  output/tsconfig.json
  package.json
  src/cli.ts
  src/domain.ts
  src/index.ts
  test/expected-model1.txt
  test/expected-model4.txt
  test/expected-route4.txt
  test/index.ts
  test/source4.json
  tsconfig.json
  tslint.json
  typings-checker/index.ts
  typings-checker/tsconfig.json
Labels: in review
