Repository buildo/metarpheus-io-ts, pull requests merged in 2018-12, with the labels that each got.

#58 Handle Option inside containers
  .gitignore
  .travis.yml
  package.json
  src/index.ts
  test/expected-model4.txt
  test/source4.json
Labels: in review

#63 Handle non-string Map keys
  src/index.ts
  test/expected-model-any.txt
  test/expected-model3.txt
  test/source3.json
Labels: bug, in review

#65 #57: optional values in scala translates wrongly in `io-ts` (closes #57)
  package.json
  test/expected-model-any.txt
  test/expected-model1.txt
  test/expected-model2.txt
  test/expected-model3.txt
  test/expected-model4.txt
Labels: defect, waiting for merge

#67 #66: use `jest` instead of `mocha` (closes #66)
  package.json
  test/__snapshots__/main.test.ts.snap
  test/expected-model-any.txt
  test/expected-model1.txt
  test/expected-model2.txt
  test/expected-model3.txt
  test/expected-model4.txt
  test/expected-route3.txt
  test/expected-route4.txt
  test/main.test.ts
Labels: DX, waiting for merge

#69 #64: Remove custom dictionaryCombinator (closes #64)
  src/index.ts
Labels: waiting for merge

#72 Add support for legacy newtype encoding
  output/index.ts
  package.json
  src/index.ts
  test/__snapshots__/main.test.ts.snap
  test/main.test.ts
  test/source-legacy-newtype.json
Labels: waiting for merge

#70 #30: correctly serialize api route params (and body, and query) (closes #30)
  package.json
  src/index.ts
  test/__snapshots__/main.test.ts.snap
Labels: bug, in review
