Repository buildo/metarpheus-io-ts, pull requests merged in 2019-09, with the labels that each got.

#108 #107: invalid API responses cause an uncaught Promise rejection instead of a proper TaskEither failure (closes #107)
  package.json
  src/index.ts
  test/__snapshots__/main.test.ts.snap
Labels: FE maint, bug, waiting for merge

#110 #109: `genericCombinator` is mixing runtime and static type parameters when newtypes are involved (closes #109)
  src/index.ts
  test/__snapshots__/main.test.ts.snap
Labels: bug, in review

#111 Fixing some security advisories by updating deps (closes #112)
  package.json
Labels: waiting for merge
